version: '3.4'

services:
  database:
    image: mysql:5
    container_name: database
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    links:
      - database:mysql
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_CACHE', false );
          define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST']);
          define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST']);
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network

  
volumes:
  wordpress:
  database:

networks:
  app-network:
    driver: bridge
      